apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: {{ .Values.fullnameOverride }}
spec:
  serviceAccountName: {{ template "auth.fullname" . }}
  serviceMonitorSelector:
    matchLabels:
      type: {{ .Values.fullnameOverride }}
  resources:
    requests:
      memory: 400Mi
  enableAdminAPI: false