{{- $connectionString := printf "Host=%s;Port=%s;Database=%s;Username=%s;Password=%s" .Values.auth.postgres.service (.Values.auth.postgres.port | toString) .Values.auth.accountDBName .Values.postgresUsername .Values.postgresPassword -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ template "auth.fullname" . }}-secrets
  labels:
    app: {{ template "auth.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
  SecretKey: {{ .Values.auth.secretKey | b64enc | quote }}
  IdentityDbContext: {{ $connectionString | b64enc | quote }}
  PostgresHost: {{ .Values.auth.postgres.service | b64enc | quote }}
  PostgresPort: {{ .Values.auth.postgres.port | toString | b64enc | quote }}
  PostgresDatabase: {{ .Values.auth.accountDBName | b64enc | quote }}
  PostgresUsername: {{ .Values.postgresUsername | b64enc | quote }}
  PostgresPassword: {{ .Values.postgresPassword | b64enc | quote }}
