apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "auth.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    type: {{ .Values.fullnameOverride }}
spec:
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  endpoints:
  - port: http
    interval: 30s
  selector:
    matchLabels:
      app: {{ include "auth.fullname" . }}
      app.kubernetes.io/name: {{ include "auth.name" . }}