apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: "{{ template "demo.fullname" . }}-hpa"
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: {{ template "demo.fullname" . }}
  minReplicas: {{ .Values.hpa.minReplicaCount }}
  maxReplicas: {{ .Values.hpa.maxReplicaCount }}
{{- with .Values.metrics }}
  metrics:
  {{- toYaml . | nindent 8 }}
{{- end }}